package com.kindykoo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBabyName(java.lang.String babyName) {
		set("babyName", babyName);
		return (M)this;
	}
	
	public java.lang.String getBabyName() {
		return getStr("babyName");
	}

	public M setBabyAge(java.lang.Integer babyAge) {
		set("babyAge", babyAge);
		return (M)this;
	}
	
	public java.lang.Integer getBabyAge() {
		return getInt("babyAge");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public M setAvatarUrl(java.lang.String avatarUrl) {
		set("avatarUrl", avatarUrl);
		return (M)this;
	}
	
	public java.lang.String getAvatarUrl() {
		return getStr("avatarUrl");
	}

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public M setRole(java.lang.String role) {
		set("role", role);
		return (M)this;
	}
	
	public java.lang.String getRole() {
		return getStr("role");
	}

	public M setBinded(java.lang.Boolean binded) {
		set("binded", binded);
		return (M)this;
	}
	
	public java.lang.Boolean getBinded() {
		return get("binded");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setBakNum(java.lang.Integer bakNum) {
		set("bakNum", bakNum);
		return (M)this;
	}
	
	public java.lang.Integer getBakNum() {
		return getInt("bakNum");
	}

	public M setBakChar(java.lang.String bakChar) {
		set("bakChar", bakChar);
		return (M)this;
	}
	
	public java.lang.String getBakChar() {
		return getStr("bakChar");
	}

}
