package com.kindykoo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setNickName(java.lang.String nickName) {
		set("nickName", nickName);
		return (M)this;
	}
	
	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
		return (M)this;
	}
	
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public M setContact(java.lang.String contact) {
		set("contact", contact);
		return (M)this;
	}
	
	public java.lang.String getContact() {
		return getStr("contact");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setRelationship(java.lang.String relationship) {
		set("relationship", relationship);
		return (M)this;
	}
	
	public java.lang.String getRelationship() {
		return getStr("relationship");
	}

	public M setRegisterDate(java.util.Date registerDate) {
		set("registerDate", registerDate);
		return (M)this;
	}
	
	public java.util.Date getRegisterDate() {
		return get("registerDate");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setVipCardNo(java.lang.String vipCardNo) {
		set("vipCardNo", vipCardNo);
		return (M)this;
	}
	
	public java.lang.String getVipCardNo() {
		return getStr("vipCardNo");
	}

	public M setVipType(java.lang.String vipType) {
		set("vipType", vipType);
		return (M)this;
	}
	
	public java.lang.String getVipType() {
		return getStr("vipType");
	}

	public M setMainUserFlag(java.lang.String mainUserFlag) {
		set("mainUserFlag", mainUserFlag);
		return (M)this;
	}
	
	public java.lang.String getMainUserFlag() {
		return getStr("mainUserFlag");
	}

	public M setMainUserName(java.lang.String mainUserName) {
		set("mainUserName", mainUserName);
		return (M)this;
	}
	
	public java.lang.String getMainUserName() {
		return getStr("mainUserName");
	}

	public M setBeginDate(java.util.Date beginDate) {
		set("beginDate", beginDate);
		return (M)this;
	}
	
	public java.util.Date getBeginDate() {
		return get("beginDate");
	}

	public M setEndDate(java.util.Date endDate) {
		set("endDate", endDate);
		return (M)this;
	}
	
	public java.util.Date getEndDate() {
		return get("endDate");
	}

	public M setDisableCourseCount(java.lang.Integer disableCourseCount) {
		set("disableCourseCount", disableCourseCount);
		return (M)this;
	}
	
	public java.lang.Integer getDisableCourseCount() {
		return getInt("disableCourseCount");
	}

	public M setActivityCourseCount(java.lang.Integer activityCourseCount) {
		set("activityCourseCount", activityCourseCount);
		return (M)this;
	}
	
	public java.lang.Integer getActivityCourseCount() {
		return getInt("activityCourseCount");
	}

	public M setUseCourseCount(java.lang.Integer useCourseCount) {
		set("useCourseCount", useCourseCount);
		return (M)this;
	}
	
	public java.lang.Integer getUseCourseCount() {
		return getInt("useCourseCount");
	}

	public M setRemainCourseCount(java.lang.Integer remainCourseCount) {
		set("remainCourseCount", remainCourseCount);
		return (M)this;
	}
	
	public java.lang.Integer getRemainCourseCount() {
		return getInt("remainCourseCount");
	}

	public M setPresentCourseCount(java.lang.Integer presentCourseCount) {
		set("presentCourseCount", presentCourseCount);
		return (M)this;
	}
	
	public java.lang.Integer getPresentCourseCount() {
		return getInt("presentCourseCount");
	}

	public M setVipCourseCount(java.lang.Integer vipCourseCount) {
		set("vipCourseCount", vipCourseCount);
		return (M)this;
	}
	
	public java.lang.Integer getVipCourseCount() {
		return getInt("vipCourseCount");
	}

	public M setCourseCount(java.lang.Integer courseCount) {
		set("courseCount", courseCount);
		return (M)this;
	}
	
	public java.lang.Integer getCourseCount() {
		return getInt("courseCount");
	}

	public M setWeekReserveCount(java.lang.Integer weekReserveCount) {
		set("weekReserveCount", weekReserveCount);
		return (M)this;
	}
	
	public java.lang.Integer getWeekReserveCount() {
		return getInt("weekReserveCount");
	}

	public M setWeekMaxCount(java.lang.Integer weekMaxCount) {
		set("weekMaxCount", weekMaxCount);
		return (M)this;
	}
	
	public java.lang.Integer getWeekMaxCount() {
		return getInt("weekMaxCount");
	}

	public M setCounts(java.lang.Integer counts) {
		set("counts", counts);
		return (M)this;
	}
	
	public java.lang.Integer getCounts() {
		return getInt("counts");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public M setRemainAmount(java.lang.Integer remainAmount) {
		set("remainAmount", remainAmount);
		return (M)this;
	}
	
	public java.lang.Integer getRemainAmount() {
		return getInt("remainAmount");
	}

	public M setAllAmount(java.lang.Integer allAmount) {
		set("allAmount", allAmount);
		return (M)this;
	}
	
	public java.lang.Integer getAllAmount() {
		return getInt("allAmount");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Boolean getEnable() {
		return get("enable");
	}

}
