package com.kindykoo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseReserveCourseHistory<M extends BaseReserveCourseHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStudentName(java.lang.String studentName) {
		set("studentName", studentName);
		return (M)this;
	}
	
	public java.lang.String getStudentName() {
		return getStr("studentName");
	}

	public M setCourseTableID(java.lang.Integer courseTableID) {
		set("courseTableID", courseTableID);
		return (M)this;
	}
	
	public java.lang.Integer getCourseTableID() {
		return getInt("courseTableID");
	}

	public M setWeekCount(java.lang.Integer weekCount) {
		set("weekCount", weekCount);
		return (M)this;
	}
	
	public java.lang.Integer getWeekCount() {
		return getInt("weekCount");
	}

	public M setWeek(java.lang.String week) {
		set("week", week);
		return (M)this;
	}
	
	public java.lang.String getWeek() {
		return getStr("week");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public M setCourseTime(java.lang.String courseTime) {
		set("courseTime", courseTime);
		return (M)this;
	}
	
	public java.lang.String getCourseTime() {
		return getStr("courseTime");
	}

	public M setCourse(java.lang.String course) {
		set("course", course);
		return (M)this;
	}
	
	public java.lang.String getCourse() {
		return getStr("course");
	}

	public M setTeacher1(java.lang.String teacher1) {
		set("teacher1", teacher1);
		return (M)this;
	}
	
	public java.lang.String getTeacher1() {
		return getStr("teacher1");
	}

	public M setTeacher2(java.lang.String teacher2) {
		set("teacher2", teacher2);
		return (M)this;
	}
	
	public java.lang.String getTeacher2() {
		return getStr("teacher2");
	}

	public M setClassroom(java.lang.String classroom) {
		set("classroom", classroom);
		return (M)this;
	}
	
	public java.lang.String getClassroom() {
		return getStr("classroom");
	}

	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setReserveType(java.lang.String reserveType) {
		set("reserveType", reserveType);
		return (M)this;
	}
	
	public java.lang.String getReserveType() {
		return getStr("reserveType");
	}

	public M setReserveTime(java.util.Date reserveTime) {
		set("reserveTime", reserveTime);
		return (M)this;
	}
	
	public java.util.Date getReserveTime() {
		return get("reserveTime");
	}

	public M setEnableMan(java.lang.String enableMan) {
		set("enableMan", enableMan);
		return (M)this;
	}
	
	public java.lang.String getEnableMan() {
		return getStr("enableMan");
	}

	public M setEnableTime(java.util.Date enableTime) {
		set("enableTime", enableTime);
		return (M)this;
	}
	
	public java.util.Date getEnableTime() {
		return get("enableTime");
	}

	public M setConfirmMan(java.lang.String confirmMan) {
		set("confirmMan", confirmMan);
		return (M)this;
	}
	
	public java.lang.String getConfirmMan() {
		return getStr("confirmMan");
	}

	public M setConfirmTime(java.util.Date confirmTime) {
		set("confirmTime", confirmTime);
		return (M)this;
	}
	
	public java.util.Date getConfirmTime() {
		return get("confirmTime");
	}

	public M setPresent(java.lang.Boolean present) {
		set("present", present);
		return (M)this;
	}
	
	public java.lang.Boolean getPresent() {
		return get("present");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
