package com.kindykoo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourseTable<M extends BaseCourseTable<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWeekCount(java.lang.Integer weekCount) {
		set("weekCount", weekCount);
		return (M)this;
	}
	
	public java.lang.Integer getWeekCount() {
		return getInt("weekCount");
	}

	public M setWeek(java.lang.String week) {
		set("week", week);
		return (M)this;
	}
	
	public java.lang.String getWeek() {
		return getStr("week");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public M setBeginTime(java.util.Date beginTime) {
		set("beginTime", beginTime);
		return (M)this;
	}
	
	public java.util.Date getBeginTime() {
		return get("beginTime");
	}

	public M setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public M setCourseTime(java.lang.String courseTime) {
		set("courseTime", courseTime);
		return (M)this;
	}
	
	public java.lang.String getCourseTime() {
		return getStr("courseTime");
	}

	public M setCourse(java.lang.String course) {
		set("course", course);
		return (M)this;
	}
	
	public java.lang.String getCourse() {
		return getStr("course");
	}

	public M setMinAge(java.lang.Integer minAge) {
		set("minAge", minAge);
		return (M)this;
	}
	
	public java.lang.Integer getMinAge() {
		return getInt("minAge");
	}

	public M setMaxAge(java.lang.Integer maxAge) {
		set("maxAge", maxAge);
		return (M)this;
	}
	
	public java.lang.Integer getMaxAge() {
		return getInt("maxAge");
	}

	public M setTeacher1(java.lang.String teacher1) {
		set("teacher1", teacher1);
		return (M)this;
	}
	
	public java.lang.String getTeacher1() {
		return getStr("teacher1");
	}

	public M setTeacher2(java.lang.String teacher2) {
		set("teacher2", teacher2);
		return (M)this;
	}
	
	public java.lang.String getTeacher2() {
		return getStr("teacher2");
	}

	public M setClassroom(java.lang.String classroom) {
		set("classroom", classroom);
		return (M)this;
	}
	
	public java.lang.String getClassroom() {
		return getStr("classroom");
	}

	public M setStuNumber(java.lang.Integer stuNumber) {
		set("stuNumber", stuNumber);
		return (M)this;
	}
	
	public java.lang.Integer getStuNumber() {
		return getInt("stuNumber");
	}

	public M setMaxNumber(java.lang.Integer maxNumber) {
		set("maxNumber", maxNumber);
		return (M)this;
	}
	
	public java.lang.Integer getMaxNumber() {
		return getInt("maxNumber");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setFixedNum(java.lang.Integer fixedNum) {
		set("fixedNum", fixedNum);
		return (M)this;
	}
	
	public java.lang.Integer getFixedNum() {
		return getInt("fixedNum");
	}

	public M setMaxFixedNum(java.lang.Integer maxFixedNum) {
		set("maxFixedNum", maxFixedNum);
		return (M)this;
	}
	
	public java.lang.Integer getMaxFixedNum() {
		return getInt("maxFixedNum");
	}

	public M setAllowFixed(java.lang.Boolean allowFixed) {
		set("allowFixed", allowFixed);
		return (M)this;
	}
	
	public java.lang.Boolean getAllowFixed() {
		return get("allowFixed");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Boolean getEnable() {
		return get("enable");
	}

}
