package com.kindykoo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("classroom", "id", Classroom.class);
		arp.addMapping("course", "id", Course.class);
		arp.addMapping("courseTable", "id", CourseTable.class);
		arp.addMapping("courseTime", "id", CourseTime.class);
		arp.addMapping("logs", "id", Logs.class);
		arp.addMapping("menu", "id", Menu.class);
		arp.addMapping("paras", "id", Paras.class);
		arp.addMapping("reserveCourse", "id", ReserveCourse.class);
		arp.addMapping("reserveCourseHistory", "id", ReserveCourseHistory.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("teacher", "id", Teacher.class);
		arp.addMapping("user", "id", User.class);
	}
}

