package com.kindykoo.common.model;

import com.kindykoo.common.model.base.BaseCourseTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseTime extends BaseCourseTime<CourseTime> {
	public static final CourseTime dao = new CourseTime().dao();
}
