package com.kindykoo.common.model;

import com.kindykoo.common.model.base.BaseCourseTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseTable extends BaseCourseTable<CourseTable> {
	public static final CourseTable dao = new CourseTable().dao();
}
