package com.kindykoo.common.model;

import com.kindykoo.common.model.base.BaseLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Logs extends BaseLogs<Logs> {
	public static final Logs dao = new Logs().dao();
}
