package com.kindykoo.common.model;

import com.kindykoo.common.model.base.BaseParas;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Paras extends BaseParas<Paras> {
	public static final Paras dao = new Paras().dao();
}
