package com.kindykoo.common.model;

import com.kindykoo.common.model.base.BaseReserveCourseHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReserveCourseHistory extends BaseReserveCourseHistory<ReserveCourseHistory> {
	public static final ReserveCourseHistory dao = new ReserveCourseHistory().dao();
}
