package com.kindykoo.common.model;

import com.kindykoo.common.model.base.BaseReserveCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReserveCourse extends BaseReserveCourse<ReserveCourse> {
	public static final ReserveCourse dao = new ReserveCourse().dao();
}
